# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: server
generate:
  models: true
  gin-server: true
  strict-server: true
output-options:
  skip-prune: true
import-mapping:
  ../../components/common/main.yaml: "testoapi/gens/models/common"
  ../../components/customer_manager/main.yaml: "testoapi/gens/models/customer_manager"
  ../../components/flow_manager/main.yaml: "testoapi/gens/models/flow_manager"
  ../../components/agent_manager/main.yaml: "testoapi/gens/models/agent_manager"
  ../../components/number_manager/main.yaml: "testoapi/gens/models/number_manager"
  ../../components/billing_manager/main.yaml: "testoapi/gens/models/billing_manager"
  ../../components/call_manager/main.yaml: "testoapi/gens/models/call_manager"
  ../../components/campaign_manager/main.yaml: "testoapi/gens/models/campaign_manager"
  ../../components/chatbot_manager/main.yaml: "testoapi/gens/models/chatbot_manager"
  ../../components/chat_manager/main.yaml: "testoapi/gens/models/chat_manager"
