openapi: 3.0.0
info:
  title: VoipBin API
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1.0
paths:
  /accesskeys:
    $ref: './paths/accesskeys/main.yaml'
  /accesskeys/{id}:
    $ref: './paths/accesskeys/id.yaml'
  /activeflows:
    $ref: './paths/activeflows/main.yaml'
  /activeflows/{id}:
    $ref: './paths/activeflows/id.yaml'
  /activeflows/{id}/stop:
    $ref: './paths/activeflows/id_stop.yaml'